let shopItemsData = [
    {
      id: "fcc1",
      name: "Yummy Donuts",
      price: 500,
      img: "images/donuts2.jpg",
    },
    {
      id: "fcc2",
      name: "Chin-Chin",
      price: 1000,
      img: "images/chin-chin1.jpg",
    },
    {
      id: "fcc3",
      name: "Popcorn & Coke",
      price: 250,
      img: "images/popcorn-and-coke.jpg",
    },
    {
      id: "fcc4",
      name: "Popcorn-S",
      price: 300,
      img: "images/popcorn1.jpg",
    },
    {
      id: "fcc5",
      name: "Popcorn-M",
      price: 500,
      img: "images/popcorn3.jpg",
    },
    {
      id: "fcc6",
      name: "Popcorn-L",
      price: 500,
      img: "images/popcorn2.jpg",
    },
    {
      id: "fcc7",
      name: "Sausage-rolls",
      price: 1000,
      img: "images/pork-sausage-rolls.jpg",
    },
    {
      id: "fcc8",
      name: "Tasty-cinnamon-buns",
      price: 250,
      img: "images/tasty-cinnamon-buns.jpg",
    },
    {
      id: "fcc9",
      name: "Buns",
      price: 300,
      img: "images/buns.jpg",
    },
    {
      id: "fcc10",
      name: "Croissant",
      price: 300,
      img: "images/croissant.jpg",
    },
    {
      id: "fcc11",
      name: "Yummy Croissant",
      price: 500,
      img: "images/croissant2.jpg",
    },
    {
      id: "fcc12",
      name: "Meat-pie",
      price: 1000,
      img: "images/meat-pie.jpg",
    },
    {
      id: "fcc13",
      name: "Sweet-cake",
      price: 250,
      img: "images/sweet-cake.jpg",
    },
    {
      id: "fcc14",
      name: "Assorted-donuts",
      price: 300,
      img: "images/assorted-donuts.jpg",
    },
    {
      id: "fcc15",
      name: "Vintage-cupcakes",
      price: 300,
      img: "images/vintage-cupcakes.jpg",
    },
    {
      id: "fcc16",
      name: "Colorful-cupcakes",
      price: 500,
      img: "images/colorful-cupcakes.jpg",
    },
    {
      id: "fcc17",
      name: "Chocolate-cake",
      price: 1000,
      img: "images/chocolate-cake.jpg",
    },
    {
      id: "fcc18",
      name: "Cupcakes",
      price: 250,
      img: "images/cupcakes.jpg",
    },
    {
      id: "fcc19",
      name: "Hot-dog-buns",
      price: 300,
      img: "images/hot-dog-buns.jpg",
    },
    {
      id: "fcc20",
      name: "Hamburger-buns",
      price: 300,
      img: "images/hamburger-buns.jpg",
    },
    {
      id: "fcc21",
      name: "Crusty-baguettes",
      price: 300,
      img: "images/crusty-mini-baguettes.jpg",
    },
    {
      id: "fcc22",
      name: "Hot-burgers",
      price: 300,
      img: "images/hot-burgers-french-fries.jpg",
    },
    {
      id: "fcc23",
      name: "hot-cross-buns",
      price: 300,
      img: "images/hot-cross-buns.jpg",
    },
    {
      id: "fcc24",
      name: "assorted-donuts-carnival",
      price: 300,
      img: "images/assorted-donuts-carnival.jpg",
    },
    {
      id: "fcc23",
      name: "Donuts",
      price: 300,
      img: "images/donuts1.jpg",
    },
    {
      id: "fcc24",
      name: "Donuts-in-box",
      price: 300,
      img: "images/delicious-donuts-in-box.jpg",
    },
    {
      id: "fcc25",
      name: "Delicous-donuts",
      price: 300,
      img: "images/colorful-donuts.jpg",
    },
    {
      id: "fcc26",
      name: "Chocolate-cookies",
      price: 300,
      img: "images/chocolate-cookies.jpg",
    },
    {
      id: "fcc27",
      name: "Dessert-cream-chocolate",
      price: 300,
      img: "images/dessert-cream-chocolate.jpg",
    },
    {
      id: "fcc28",
      name: "Strawberry-layered-dessert",
      price: 300,
      img: "images/layered-dessert.jpg",
    },
  ];
  